//tealium universal tag - utag.51 ut4.0.201605032019, Copyright 2016 Tealium.com Inc. All Rights Reserved.
var pwidget_config=pwidget_config||{};try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.scriptrequested=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":("https:"==document.location.protocol?"https://s":"http://i")+".po.st/share/script/post-widget.js","publisherKey":"underground","divid":"","size":"small"||"medium","addButtons":"","trackAddressBar":("false"==="true"?true:false),"copypaste":("false"==="true"?true:false),"shareQuote":("false"==="true"?true:false)};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
if(u.data.divid&&!u.scriptrequested){u.data.counter=(u.data.counter==="true")?" pw-counter":"";d='<div class="pw-widget pw-size-'+u.data.size+'">';u.data.addButtons=u.data.addButtons.split(",");for(f=0;f<u.data.addButtons.length;f++){d+='<a class="pw-button-'+u.data.addButtons[f]+u.data.counter+'"></a>';}
d+='</div>';e=document.getElementById(u.data.divid);try{e.innerHTML+=d;}catch(error){utag.DB("ERROR:51:"+error);}}
u.urlToArray=function(){var postCurrentURLString=decodeURIComponent(window.location.href);var postCurrentURLSplitHashArray=postCurrentURLString.split('#');return(postCurrentURLSplitHashArray);};u.URLValidation=function(){var urlSegments=u.urlToArray();if(urlSegments.length===1){return'valid';}
else{return'invalid';}}
u.setConfiguration=function(){var urlState=u.URLValidation();var configuration={};if(urlState==='valid'){configuration={trackAddressBar:u.data.trackAddressBar,copypaste:u.data.copypaste,shareQuote:u.data.shareQuote,defaults:{afterShare:false}};}
else{configuration={trackAddressBar:false,copypaste:false,shareQuote:true,defaults:{afterShare:false}};}
return configuration;}
pwidget_config=u.setConfiguration();if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url+"#publisherKey="+u.data.publisherKey,"loc":"script","id":'utag_51'});}
}};utag.o[loader].loader.LOAD(id);}("51","weather.wunderground"));}catch(error){utag.DB(error);}
